#ifndef BLOOPER_PROJECTS_MENU_WINDOW_HPP
#define BLOOPER_PROJECTS_MENU_WINDOW_HPP


BLOOPER_NAMESPACE_BEGIN

class ProjectsMenuWindow : juce::DocumentWindow
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_PROJECTS_MENU_WINDOW_HPP
