#ifndef BLOOPER_PROJECT_COMPONENT_HPP
#define BLOOPER_PROJECT_COMPONENT_HPP


BLOOPER_NAMESPACE_BEGIN

class ProjectComponent : juce::Component
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_PROJECT_COMPONENT_HPP
