#ifndef BLOOPER_PANELS_COMPONENT_HPP
#define BLOOPER_PANELS_COMPONENT_HPP


BLOOPER_NAMESPACE_BEGIN

class PanelsComponent : public juce::Component
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_PANELS_COMPONENT_HPP
