#ifndef BLOOPER_SETTINGS_MENU_COMPONENT_HPP
#define BLOOPER_SETTINGS_MENU_COMPONENT_HPP


BLOOPER_NAMESPACE_BEGIN

class SettingsMenuComponent : public juce::Component
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_SETTINGS_MENU_COMPONENT_HPP
