#ifndef BLOOPER_SETTINGS_MENU_WINDOW_HPP
#define BLOOPER_SETTINGS_MENU_WINDOW_HPP


BLOOPER_NAMESPACE_BEGIN

class SettingsMenuWindow : public juce::DocumentWindow
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_SETTINGS_MENU_WINDOW_HPP
