#ifndef BLOOPER_PLUGINS_MENU_COMPONENT_HPP
#define BLOOPER_PLUGINS_MENU_COMPONENT_HPP


#include <blooper/internal/internal.hpp>


BLOOPER_NAMESPACE_BEGIN

BLOOPER_NAMESPACE_END


#endif // BLOOPER_PLUGINS_MENU_COMPONENT_HPP
