#ifndef BLOOPER_DEVICES_MENU_COMPONENT_HPP
#define BLOOPER_DEVICES_MENU_COMPONENT_HPP


BLOOPER_NAMESPACE_BEGIN

class DevicesMenuComponent : public juce::Component
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_DEVICES_MENU_COMPONENT_HPP
