#ifndef BLOOPER_DEVICES_MENU_WINDOW_HPP
#define BLOOPER_DEVICES_MENU_WINDOW_HPP


BLOOPER_NAMESPACE_BEGIN

class DevicesMenuWindow : public juce::DocumentWindow
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_DEVICES_MENU_WINDOW_HPP
