#ifndef BLOOPER_HOW_TO_COMPONENT_HPP
#define BLOOPER_HOW_TO_COMPONENT_HPP


BLOOPER_NAMESPACE_BEGIN

class HowToComponent : public juce::Component
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_HOW_TO_COMPONENT_HPP
