#ifndef BLOOPER_TUTORIAL_COMPONENT_HPP
#define BLOOPER_TUTORIAL_COMPONENT_HPP


BLOOPER_NAMESPACE_BEGIN

class TutorialComponent : public juce::Component
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_TUTORIAL_COMPONENT_HPP
