#ifndef BLOOPER_DEV_EDIT_COMPONENT_HPP
#define BLOOPER_DEV_EDIT_COMPONENT_HPP


BLOOPER_DEV_NAMESPACE_BEGIN

class EditComponent : public juce::Component
{
};

BLOOPER_DEV_NAMESPACE_END


#endif // BLOOPER_DEV_EDIT_COMPONENT_HPP
