#ifndef BLOOPER_DEV_PROJECT_COMPONENT_HPP
#define BLOOPER_DEV_PROJECT_COMPONENT_HPP


BLOOPER_DEV_NAMESPACE_BEGIN

class ProjectComponent : public juce::Component
{
};

BLOOPER_DEV_NAMESPACE_END


#endif // BLOOPER_DEV_PROJECT_COMPONENT_HPP
