#ifndef BLOOPER_DEV_VALUE_TREE_COMPONENT_HPP
#define BLOOPER_DEV_VALUE_TREE_COMPONENT_HPP


BLOOPER_DEV_NAMESPACE_BEGIN

class ValueTreeComponent : public juce::Component
{
};

BLOOPER_DEV_NAMESPACE_END


#endif // BLOOPER_DEV_VALUE_TREE_COMPONENT_HPP
