#ifndef BLOOPER_CONTEXT_FUNCTIONS_HPP
#define BLOOPER_CONTEXT_FUNCTIONS_HPP
#pragma once

#include <blooper/internal/macros/namespaces.hpp>

BLOOPER_NAMESPACE_BEGIN

BLOOPER_NAMESPACE_END

#endif // BLOOPER_CONTEXT_FUNCTIONS_HPP
