#ifndef BLOOPER_TAKE_COMPONENT_FACTORY_HPP
#define BLOOPER_TAKE_COMPONENT_FACTORY_HPP

#include <blooper/internal/abstract/takes.hpp>

BLOOPER_NAMESPACE_BEGIN

BLOOPER_NAMESPACE_END

#endif // BLOOPER_TAKE_COMPONENT_FACTORY_HPP
