#ifndef BLOOPER_TRACK_COMPONENT_FACTORY_HPP
#define BLOOPER_TRACK_COMPONENT_FACTORY_HPP

#include <blooper/internal/abstract/tracks.hpp>

BLOOPER_NAMESPACE_BEGIN

BLOOPER_NAMESPACE_END

#endif // BLOOPER_TRACK_COMPONENT_FACTORY_HPP
