#ifndef BLOOPER_HEADER_MENU_BAR_COMPONENT_HPP
#define BLOOPER_HEADER_MENU_BAR_COMPONENT_HPP


BLOOPER_NAMESPACE_BEGIN

class HeaderMenuBarComponent : public juce::Component
{
};

BLOOPER_NAMESPACE_END


#endif // BLOOPER_HEADER_MENU_BAR_COMPONENT_HPP
